LungsCancerPrediction/urls.py
from unicodedata import name
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from lungs_app.views import *
# from .api import router

urlpatterns = [
    # path('api/sensoviz/', include(router.urls)),
    path('admin/', admin.site.urls),
    path('', Home, name="home"),
    path('patient_home', User_Home,name="patient_home"),
    path('doctor_home', Doctor_Home,name="doctor_home"),
    path('admin_home', Admin_Home,name="admin_home"),
    path('about/', About,name="about"),
    path('contact/', Contact,name="contact"),
    path('gallery', Gallery,name="gallery"),
    path('login/', Login_User,name="login"),
    path('login_admin/', Login_admin,name="login_admin"),
    path('signup', Signup_User,name="signup"),
    path('logout/', Logout,name="logout"),
    path('change_password', Change_Password,name="change_password"),
    # path('prdict_heart_disease', prdict_heart_disease,name="prdict_heart_disease"),
    path('add_heartdetail', add_heartdetail,name="add_heartdetail"),
    path('view_search_pat', view_search_pat,name="view_search_pat"),

    path('view_doctor', View_Doctor,name="view_doctor"),
    path('add_doctor', add_doctor,name="add_doctor"),
    path('change_doctor/<int:pid>/', add_doctor,name="change_doctor"),
    path('view_patient', View_Patient,name="view_patient"),
    path('view_feedback', View_Feedback,name="view_feedback"),
    path('edit_profile', Edit_My_deatail,name="edit_profile"),
    path('profile_doctor', View_My_Detail,name="profile_doctor"),
    path('sent_feedback', sent_feedback,name="sent_feedback"),

    path('delete_searched/<int:pid>', delete_searched, name="delete_searched"),
    path('delete_doctor<int:pid>', delete_doctor, name="delete_doctor"),
    path('assign_status<int:pid>', assign_status, name="assign_status"),
    path('delete_patient<int:pid>', delete_patient, name="delete_patient"),
    path('delete_feedback<int:pid>', delete_feedback, name="delete_feedback"),
    path('predict_desease/<str:pred>/<str:accuracy>/', predict_desease, name="predict_desease"),

    path('add_genralhealth', add_genralhealth, name="add_genralhealth"),

    path('search_blood', search_blood, name="search_blood"),
    path('donate_blood', donate_blood, name="donate_blood"),

    path('request_blood', request_blood, name="request_blood"),
    path('donator_blood', donator_blood, name="donator_blood"),

    path('change_status/<int:pid>/', change_status, name="change_status"),

    path('add_lungs_pred', add_lungs_pred, name="add_lungs_pred"),
    path('detail_searched/<int:pid>', detail_searched, name="detail_searched"),

]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

lungs_app/models.py
from operator import mod
from pyexpat import model
from re import M
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
DOCTOR_STATUS = ((1, 'Authorize'), (2, 'UnAuthorize'))

class Patient(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    contact = models.CharField(max_length=100, null=True)
    address = models.CharField(max_length=100, null=True)
    dob = models.DateField(null=True)
    image = models.FileField(null=True)

    def __str__(self):
        return self.user.username

class Doctor(models.Model):
    status = models.IntegerField(DOCTOR_STATUS, null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    contact = models.CharField(max_length=100, null=True)
    address = models.CharField(max_length=100, null=True)
    category = models.CharField(max_length=100, null=True)
    doj = models.DateField(null=True)
    dob = models.DateField(null=True)
    image = models.FileField(null=True)

    def __str__(self):
        return self.user.username

class Admin_Helath_CSV(models.Model):
    name = models.CharField(max_length=100, null=True)
    csv_file = models.FileField(null=True, blank=True)

    def __str__(self):
        return self.name

class Search_Data(models.Model):
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE, null=True)
    prediction_accuracy = models.CharField(max_length=100,null=True,blank=True)
    result = models.CharField(max_length=100,null=True,blank=True)
    values_list = models.CharField(max_length=100,null=True,blank=True)
    predict_for = models.CharField(max_length=100,null=True,blank=True)
    uploaded  = models.FileField(null=True, blank=True)
    output  = models.FileField(null=True, blank=True)
    created = models.DateTimeField(auto_now=True,null=True)

    def __str__(self):
        return self.patient.user.username

class Feedback(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    messages = models.TextField(null=True)
    date = models.DateField(auto_now=True)

    def __str__(self):
        return self.user.user.username

class GeneralHealthProblem(models.Model):
    name = models.CharField(max_length=100, null=True, blank=True)

    def __str__(self):
        return self.name

class Blood_Donation(models.Model):
    status = models.CharField(max_length=100, null=True, blank=True)
    user = models.ForeignKey(Patient, on_delete=models.CASCADE, null=True, blank=True)
    blood_group = models.CharField(max_length=100, null=True, blank=True)
    place = models.CharField(max_length=100, null=True, blank=True)
    purpose = models.CharField(max_length=100, null=True, blank=True)
    created = models.DateTimeField(auto_now=True,null=True)
    active = models.BooleanField(null=True, blank=True, default=False)

    def __str__(self):
        return self.user.user.username

lungs_app/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django import forms
from .models import *

class DoctorForm(forms.ModelForm):
    class Meta:
        model = Doctor
        exclude = ('status', 'user', 'dob', 'doj')

lungs_app/templates/add_doctor.html
{% extends 'index.html' %}
{% load static %}
{% block body %}
	<!-- register -->
{% if error == "create" %}
<script>
    alert('Add a new Doctor Successfully');
    window.location="{% url 'view_doctor' %}";
</script>
{% endif %}


	<section class="logins py-5">
		<div class="container py-xl-5 py-lg-3">
			<div class="title-section mb-md-5 mb-4">
				<h6 class="w3ls-title-sub"></h6>
				<h3 class="w3ls-title text-uppercase text-dark font-weight-bold">Add Doctor</h3>
			</div><hr/>
			<div class="login px-sm-12" style="width:100%">
				<form action="{% if doctor %}/change_doctor/{{doctor.id}}/{% else %}/add_doctor{% endif %}" method="post" enctype="multipart/form-data">
					{% csrf_token %}
					{% if not doctor %}
					<div class="form-group row">
						<div class="col-md-6">
						<label>First Name</label>
						<input type="text" class="form-control" name="first_name" placeholder="First Name" required="">
						</div>
						<div class="col-md-6">
						<label>Last Name</label>
						<input type="text" class="form-control" name="last_name" placeholder="Last Name" required="">
						</div>
					</div>
					<div class="form-group row">
						<div class="col-md-6">
						<label>Username</label>
						<input type="text" class="form-control" name="username" placeholder="Username" required="">
						</div>
						<div class="col-md-6">
						<label>Password</label>
						<input type="password" class="form-control" name="password" placeholder="Password" required="">
						</div>
					</div>
					{% endif %}
					<div class="form-group row">
						<div class="col-md-6">
						<label>Email</label>
						<input type="email" class="form-control" name="email" placeholder="Enter Email" required="" value="{{doctor.user.email}}" {% if doctor %}readonly{% endif %}>
						</div>
						<div class="col-md-6">
						<label>Contact</label>
						<input type="text" class="form-control" name="contact" placeholder="Enter Contact" required="" value="{{doctor.contact}}">
						</div>
					</div>
					<div class="form-group row">
						<div class="col-md-6">
						<label class="mb-2">Address</label>
						<input type="text" class="form-control" name="address" id="password1" placeholder="Enter Address" required="" value="{{doctor.address}}">
						</div>
						<div class="col-md-6">
						<label>Image</label>
						<input type="file" class="form-control" name="image">
						{% if doctor %}<span>{{doctor.image.url}}</span>{% endif %}
						</div>

					</div>
					<div class="form-group row">
						<div class="col-md-12">
						<label>Specialist</label>
							<input class="form-control" name="category" placeholder="Specialist" value="{{doctor.category}}">
						</div>

					</div>
					<button type="submit" class="btn btn-primary submit mt-4">Register Doctor</button>
				</form>
			</div>
		</div>
	</section>
	<!-- //register -->

{% endblock %}

lungs_app/templates/add_genralhealth.html
{% extends 'index.html' %}
{% load static %}
{% block body %}
	<!-- register -->



	<section class="logins py-5">
		<div class="container py-xl-5 py-lg-3">
			{% if predictiondata %}

			<div class="title-section mb-md-5 mb-4">
				<h6 class="w3ls-title-sub"></h6>
				<h3 class="w3ls-title text-uppercase text-dark font-weight-bold">Result After Prediction</h3>
			</div><hr/>

			<div class="form-group row">
				<div class="col-md-6" style="border:1px solid black;padding:6px;background:blue;color:white">
					<label><b>Model Name</b></label>
				</div>
				<div class="col-md-6" style="border:1px solid black;padding:6px;background:blue;color:white">
					<label><b>Prediction Output</b></label>
				</div>
				{% for i, j in predictiondata.items %}
				<div class="col-md-6" style="border:1px solid black;padding:6px">
					<label><b>{{i}}</b></label>
				</div>
				<div class="col-md-6" style="border:1px solid black;padding:6px">
					<label>{{j}}</label>
				</div>
				{% endfor %}
			
			</div>

			{% else %}



			
			<div class="title-section mb-md-5 mb-4">
				<h6 class="w3ls-title-sub"></h6>
				<h3 class="w3ls-title text-uppercase text-dark font-weight-bold">Select Your Problem</h3>
			</div><hr/>
			<div class="login px-sm-12" style="width:100%">
				<form action="" method="post" enctype="multipart/form-data">
					{% csrf_token %}
					<div class="form-group row">

						{% for i in alldisease %}
						<div class="col-md-3" style="border:1px solid black;padding:6px">
							<label>{{i}}</label>
							<input type="radio" name="{{i}}" style="width:30px;height:15px">
						</div>
						{% endfor %}
					
					</div>
					<button type="submit" class="btn btn-primary submit mt-4">Send Data</button>
				</form>
			</div>
			{% endif %}
		</div>
	</section>
	<!-- //register -->

{% endblock %}

lungs_app/templates/add_lungs_pred.html
{% extends 'index.html' %}
{% load static %}
{% block body %}
	<!-- register -->



	<section class="logins py-5">
		<div class="container py-xl-5 py-lg-3">
			<div class="title-section mb-md-5 mb-4">
				<h6 class="w3ls-title-sub"></h6>
				<h3 class="w3ls-title text-uppercase text-dark font-weight-bold">Lungs Cancer Prediction</h3>
			</div><hr/>
			<div class="login px-sm-12" style="width:100%">
				<form action="" method="post" enctype="multipart/form-data">
					{% csrf_token %}
					<div class="form-group row">
						<div class="col-md-12">
                            <label>Upload Lungs Image</label>
                            <input type="file" class="form-control" name="file"  required="">
						</div>
					</div>
					<button type="submit" class="btn btn-primary submit mt-4">Send Lungs data</button>
				</form>
			</div>
			{% if data %}
			<div class="container">
				<div class="row">
					<div class="col-6">
						<h5>Input Image</h5>
						<img src="{{data.uploaded.url}}" style="width:600px">
					</div>
					<div class="col-6">
						<h5>Output Image</h5>
						<img src="{{data.output.url}}" style="width:600px">
					</div>
				</div>
			</div>
			{% endif %}<br><br>
			{% if clas_name == "Bengin" %}
			<div class="container">
				<div class="row">
					<div class="col-12">
						<h2 align="center" style="color:orange">You have a non – cancerous cells.</h2>
						<p>Here are some of the precautions.</p>
						<ul>
							<li>Stop smoking immediately</li>
							<li>Exercise regularly and maintain a balanced diet.</li>
							<li>Avoid carcinogens at work</li>
						</ul>
					</div>
				</div>
			</div>
			{% elif clas_name == "Normal" %}
			<div class="container">
				<div class="row">
					<div class="col-12">
						<h2 align="center" style="color:green">You are healthy.</h2>
					</div>
				</div>
			</div>
			{% elif clas_name == "Malignant" %}
			<div class="container">
				<div class="row">
					<div class="col-12">
						<h2 align="center" style="color:red">You have a cancerous cells. You may visit your nearby doctor and get treated immediately</h2>
					</div>
				</div>
			</div>
			{% endif %}
			
			{% if data and clas_name != "Normal"  %}
			<div class="container-fluid">
				<h1 align="center" style="font-weight:bold;font-family : 'Monotype Corsiva' ; color : #E6120E ;margin-top:4%">You can connect with our Doctors</h1>
				 </div><hr>
						<table id="example" class="display" style="width:100%">
						  <thead>
							<tr>
							  <th>#</th>
							  <th>Full Name</th>
							  <th>Image</th>
							  <th>Email</th>
							  <th>Contact</th>
							  <th>Address</th>
							  

						  </tr>
					  </thead>
					  <tbody>
					  {% for i in doctor %}
						<tr>
						  <td>{{forloop.counter}}</td>
						  <td>{{i.user.first_name}} {{i.user.last_name}}</td>
						  <td><img src="{{i.image.url}}" style="width:80px;height:80px"></td>
						  <td>{{i.user.email}}</td>
						  <td>{{i.contact}}</td>
						  <td>{{i.address}}</td>
						  
					  </tr>
					  {% empty %}
					  	 <td colspan="6">There is no doctor available.</td>
					  {% endfor %}
				  </tbody>
			  </table>
		  </div>
			{% endif %}

		</div>
	</section>
	<!-- //register -->

{% endblock %}

lungs_app/templates/doctor_home.html
{% extends 'index.html' %}
{% load static %}
{% block body %}
<div class="container-fluid" style="margin-top:10%;margin-bottom:2%;width:100%">
    <h2 align="center" style="font-weight:bold;font-family:roman">DOCTOR DASHBORAD</h2><hr/>
    <img src="{% static 'img/healthcare.jpg' %}" style="width:100%;height:500px">
</div>

{% endblock %}

lungs_app/templates/donator_blood.html
{% extends 'index.html' %}
{% load static %}
{% block body %}

<style>
  body {font-family: Arial, Helvetica, sans-serif;}
  
  /* The Modal (background) */
  .modal {
    display: none; /* Hidden by default */
    position: fixed; /* Stay in place */
    z-index: 1; /* Sit on top */
    padding-top: 100px; /* Location of the box */
    left: 0;
    top: 0;
    width: 100%; /* Full width */
    height: 100%; /* Full height */
    overflow: auto; /* Enable scroll if needed */
    background-color: rgb(0,0,0); /* Fallback color */
    background-color: rgba(0,0,0,0.4); /* Black w/ opacity */
  }
  
  /* Modal Content */
  .modal-content {
    position: relative;
    background-color: #fefefe;
    margin: auto;
    margin-top:6%;
    padding: 0;
    border: 1px solid #888;
    width: 60%;
    box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2),0 6px 20px 0 rgba(0,0,0,0.19);
    -webkit-animation-name: animatetop;
    -webkit-animation-duration: 0.4s;
    animation-name: animatetop;
    animation-duration: 0.4s
  }
  
  /* Add Animation */
  @-webkit-keyframes animatetop {
    from {top:-300px; opacity:0} 
    to {top:0; opacity:1}
  }
  
  @keyframes animatetop {
    from {top:-300px; opacity:0}
    to {top:0; opacity:1}
  }
  
  /* The Close Button */
  .close {
    float: right;
    font-size: 28px;
    font-weight: bold;
  }
  
  .close:hover,
  .close:focus {
    color: #000;
    text-decoration: none;
    cursor: pointer;
  }
  
  .modal-header {
    padding: 4px 16px;
    background-color: #fff;
    
  }
  
  .modal-body {padding: 2px 16px;}
  
  .modal-footer {
    padding: 2px 16px;
    background-color: #fff;
    
  }
  </style>

<div class="container-fluid" style="width:90%;margin-top:10%">
                    <div class="container-fluid">
                      <a href="/donator_blood?action=Pending">
                        <button type="button" class="btn btn-primary pull-left">Pending</button>
                      </a>
                        <h1 align="center" style="font-weight:bold;font-family : 'Monotype Corsiva' ; color : #E6120E ;margin-top:4%">
                          
                          {% if request.GET.action %} {{request.GET.action}} {% else %} All{% endif %} Donator for Blood
                          
                      <a href="/donator_blood?action=Approved">    
                        <button type="button" class="btn btn-primary pull-right">Approved</button>
                      </a>
                        </h1>
                        <div id="myModal" class="modal">
                          
                          <!-- Modal content -->
                          <div class="modal-content">
                            <div class="modal-header">
                              <h2>Request for blood</h2>
                              <span class="close">&times;</span>
                              
                            </div>
                            <div class="modal-body">
                              <div class="login px-sm-12" style="width:100%">
                                <form action="{% if doctor %}/change_doctor/{{doctor.id}}/{% else %}/add_doctor{% endif %}" method="post" enctype="multipart/form-data">
                                  {% csrf_token %}
                                  
                                  <div class="form-group row">
                                    <div class="col-md-6">
                                                    <label>Username</label>
                                                    <input type="text" class="form-control" name="username" placeholder="Username" value="{{request.user.username}}" required readonly>
                                    </div>
                                    <div class="col-md-6">
                                                    <label>Email</label>
                                                    <input type="email" class="form-control" name="email" placeholder="Enter Email" required="" value="{{request.user.email}}" readonly>
                                                </div>
                                  </div>
                                  
                                  <div class="form-group row">
                                    <div class="col-md-6">
                                                    <label>Blood Group</label>
                                                    <input type="text" class="form-control" name="bg" placeholder="Enter Blood Group">
                                    </div>
                                                <div class="col-md-6">
                                                    <label>Place</label>
                                                    <input type="text" class="form-control" name="place" placeholder="Enter Place" required>
                                    </div>
                                  </div>
                                            <br>
                                  <div class="form-group row">
                                    <div class="col-md-12">
                                                    <input type="checkbox" name="mycheck" id="mycheck" required>
                                                    <label class="mb-2">I certify that the information I am about to provided is true and complete to
                                                        the best of my knowledge. I am aware that this self declaration statement is
                                                        subject to review and verification and if such information has been falsified I
                                                        may be terminated from this organisation.</label>
                                    </div>
                                  </div>
                                  
                                  <button type="submit" class="btn btn-primary submit mt-4 pull-right">Register</button>
                                </form>
                              </div>
                            </div>
                            
                          </div>
                        
                        </div>
                         </div><hr>
                                <table id="example" class="display" style="width:100%">
                                  <thead>
                                    <tr>
                                      <th>#</th>
                                      <th>Creation Date</th>
                                      <th>Name</th>
                                      <th>Email</th>
                                      <th>Mobile</th>
                                      <th>Blood Group</th>
                                      <th>Address</th>
                                      <th>Status</th>
                                  </tr>
                              </thead>
                              <tbody>
                              {% for i in data %}
                                <tr>
                                  <td>{{forloop.counter}}</td>
                                  <td>{{i.created}}</td>
                                  <td>{{i.user.user.first_name}} {{i.user.user.last_name}}</td>
                                  <td>{{i.user.user.email}}</td>
                                  <td>{{i.user.contact}}</td>
                                  <td>{{i.blood_group}}</td>
                                  <td>{{i.place}}</td>
                                  <td>
                                    <a href="/change_status/{{i.id}}/?data={{request.get_full_path}}">
                                      <button type="button" class="btn btn-primary">{% if i.status == "Approved" %}Deny{% else %}Approve{% endif %} </button>
                                    </a>
                                  </td>
                              </tr>
                              {% endfor %}
                          </tbody>
                      </table>
                  </div>


<script>
                    // Get the modal
                    var modal = document.getElementById("myModal");
                    
                    // Get the button that opens the modal
                    var btn = document.getElementById("myBtn");
                    
                    // Get the <span> element that closes the modal
                    var span = document.getElementsByClassName("close")[0];
                    
                    // When the user clicks the button, open the modal 
                    btn.onclick = function() {
                      modal.style.display = "block";
                    }
                    
                    // When the user clicks on <span> (x), close the modal
                    span.onclick = function() {
                      modal.style.display = "none";
                    }
                    
                    // When the user clicks anywhere outside of the modal, close it
                    window.onclick = function(event) {
                      if (event.target == modal) {
                        modal.style.display = "none";
                      }
                    }
                    </script>

{% for i in messages %}
<script>
  alert("{{i}}")
</script>
{% endfor %}
{% endblock %}

lungs_app/templates/edit_doctor.html
{% extends 'index.html' %}
{% load static %}
{% block body %}
	<!-- register -->
{% ifequal error "create" %}
<script>
    alert('Doctor Updated Successfully');
    window.location="{% url 'view_doctor' %}";
</script>
{% endifequal %}


	<section class="logins py-5">
		<div class="container py-xl-5 py-lg-3">
			<div class="title-section mb-md-5 mb-4">
				<h6 class="w3ls-title-sub"></h6>
				<h3 class="w3ls-title text-uppercase text-dark font-weight-bold">Update Doctor</h3>
			</div><hr/>
			<div class="login px-sm-12" style="width:100%">
				<form action="" method="post" enctype="multipart/form-data">
					{% csrf_token %}
					<div class="form-group row">
						<div class="col-md-6">
						<label>First Name</label>
						<input type="text" class="form-control" value="{{doc.user.first_name}}" name="fname" placeholder="First Name" required="">
						</div>
						<div class="col-md-6">
						<label>Last Name</label>
						<input type="text" class="form-control" value="{{doc.user.last_name}}" name="lname" placeholder="Last Name" required="">
						</div>
					</div>
					<div class="form-group row">
						<div class="col-md-6">
						<label>Email</label>
						<input type="email" class="form-control" value="{{doc.user.email}}" name="email" placeholder="Enter Email" required="">
						</div>
						<div class="col-md-6">
						<label>Contact</label>
						<input type="text" class="form-control" name="contact" value="{{doc.contact}}" placeholder="Enter Contact" required="">
						</div>
					</div>
					<div class="form-group row">
						<div class="col-md-6">
						<label>Select Type of category[Current Category : "{{doc.category}}"]</label>
							<select class="form-control" name="type">
								{% for i in type %}
								{% ifequal i.name doc.category %}
								<option value="{{i.name}}" selected>{{i.name}}</option>
								{% else %}
								<option value="{{i.name}}">{{i.name}}</option>
								{% endifequal %}
								{% endfor %}
							</select>
						</div>
						<div class="col-md-6">
						<label>Contact</label>
						<input type="text" class="form-control" name="contact" value="{{doc.contact}}" placeholder="Enter Contact" required="">
						</div>
					</div>
					<div class="form-group row">
						<div class="col-md-6">
						<label class="mb-2">Address</label>
						<input type="text" class="form-control" value="{{doc.address}}" name="add" id="password1" placeholder="Enter Address" required="">
						</div>
						<div class="col-md-4">
						<label>Image</label>
						<input type="file" class="form-control" name="image">
						</div>
                        <div class="col-md-2">
						<img src="{{doc.image.url}}" style="width:70%;height:200px">
						</div>
					</div>
					<button type="submit" class="btn btn-primary submit mt-4">Update Doctor</button>
				</form>
			</div>
		</div>
	</section>
	<!-- //register -->

{% endblock %}

lungs_app/templates/login.html
{% extends 'index.html' %}
{% load static %}
{% block body %}
{% if error == "pat1" %}
<script>
    alert('logged in successfully');
    window.location="{% url 'patient_home' %}";
</script>
{% endif %}

{% if error == "notmember" %}
<script>
    alert('Your information verification is pending.plz login after sometimes');
    window.location="{% url 'logout' %}";
</script>
{% endif %}
{% if error == "pat2" %}
<script>
    alert('logged in successfully');
    window.location="{% url 'doctor_home' %}";
</script>
{% endif %}
{% if error == "not" %}
<script>
    alert('Username & Password are not Matching');
</script>
{% endif %}

	<!-- login -->
	<section class="logins py-5">
		<div class="container py-xl-5 py-lg-3">
			<div class="title-section mb-md-5 mb-4">
				<h6 class="w3ls-title-sub"></h6>
				<h3 class="w3ls-title text-uppercase text-dark font-weight-bold">Login Now</h3>
			</div><hr/>
			<div class="login px-sm-4 mx-auto mw-100 login-wrapper">
				<form class="login-wrapper" action="" method="post">
					{% csrf_token %}
					<div class="form-group">
						<label>Username</label>
						<input type="text" class="form-control" name="uname" placeholder="Enter Username" required="">
						<small id="emailHelp" class="form-text text-muted">We'll never share your Detail with anyone else.</small>
					</div>
					<div class="form-group">
						<label>Password</label>
						<input type="password" class="form-control" name="pwd" placeholder="Enter Your Password" required="">
					</div>
					<button type="submit" class="btn btn-primary submit mt-4">Login</button>
					<p class="text-center mt-5">
						<a href="{% url 'signup' %}"> Don't have an Account?  Register here</a>
					</p>
				</form>
			</div>
		</div>
	</section>
	<!-- //login -->
{% endblock %}

lungs_app/templates/view_feedback.html
{% extends 'index.html' %}
{% load static %}
{% block body %}

<div class="container-fluid" style="width:90%;margin-top:8%">
                    <div class="container-fluid">
                        <h1 align="center" style="font-weight:bold;font-family : 'Monotype Corsiva' ; color : #E6120E ;margin-top:4%">View Feedback</h1>
                         </div><hr>
                                <table id="example" class="display" style="width:100%">
                                  <thead>
                                    <tr>
                                      <th>#</th>
                                      <th>Full Name</th>
                                      <th>Email</th>
                                      <th>Contact</th>
                                      <th>Messages</th>
                                      <th>Action</th>

                                  </tr>
                              </thead>
                              <tbody>
                              {% for i in dis %}
                                <tr>
                                  <td>{{forloop.counter}}</td>
                                  <td>{{i.user.first_name}} {{i.user.user.last_name}}</td>
                                  <td>{{i.user.email}}</td>
                                  <td>{{i.user.patient_set.all.0.contact}}</td>
                                  <td>{{i.messages}}</td>
                                  <td style="width:150px">
                                      <a href="{% url 'delete_feedback' i.id %}" ><button class="btn btn-danger" onclick="return confirm('Are you sure?')"><i class="fa fa-trash-o"></i></button></a></td>
                              </tr>
                              {% endfor %}
                          </tbody>
                      </table>
                  </div>
{% endblock %}